// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CleanArchitecture.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddRolesAndActivation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Hand-written defaults (keep them when regenerating): existing rows stay active, and
            // users who signed themselves up owned their tenant, so they become its managers.
            // The defaults are dropped afterwards; the application always writes both columns.
            migrationBuilder.AddColumn<bool>(
                name: "is_active",
                schema: "public",
                table: "users",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.AddColumn<int>(
                name: "role",
                schema: "public",
                table: "users",
                type: "integer",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.AddColumn<bool>(
                name: "is_active",
                schema: "public",
                table: "tenants",
                type: "boolean",
                nullable: false,
                defaultValue: true);

            migrationBuilder.Sql("ALTER TABLE public.users ALTER COLUMN is_active DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE public.users ALTER COLUMN role DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE public.tenants ALTER COLUMN is_active DROP DEFAULT;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "is_active",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "role",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "is_active",
                schema: "public",
                table: "tenants");
        }
    }
}
